-- insert into messages (subject, message, response, important, create_date)
-- values ('How to post a new question?', 'Am I able to ask a question about the platform?', 'Just fill the contact form above with your question in the subject field and optionally a description in the message field and you will receive the response via your e-mail.', true, now());
--
-- insert into messages (subject, message, response, important, create_date)
-- values ('How can I view my medical history?', '', 'Go to Medical Data tab in the navigation bar', true, now());
--
-- insert into messages (subject, message, response, important, create_date)
-- values ('I forgot my password. How do I reset it?', '', null, true, now());
--
-- insert into messages (subject, message, response, important, create_date)
-- values ('What is the platform name', '', 'Medical Net', true, now());
--
-- insert into users(username, password, email, name, role_id, email_verification_token)
-- values ('admin', '$2a$05$syuu4EhTXSc1C/cx.UWfD.jThhANP6ZsAnTeiCaAHy190TYUyk/E.', null, 'Administrator', 0, null);
--
-- insert into users(username, password, email, name, role_id, email_verification_token)
-- values ('tech', '$2a$05$59lSLlwhHq5RUjAxtLJ9o.oDViE9riaE4fqBWE2gbe5DIaaIxFYNm', null, 'Tech Support', 1, null);
--
-- insert into users(username, password, email, name, role_id, email_verification_token)
-- values ('boroghin', '$2a$05$lnEIkyzxW5C9d1.KxYPJn.gx3NN/1tdgUdptIinzH7cQeMejuRZEa', 'gabrielboroghina@outlook.com', 'Gabi Boro', 2, null);
--
-- insert into users(username, password, email, name, role_id, email_verification_token)
-- values ('gabi', '$2a$05$5604J5S2Ve6g0lG9d5dxi.1iJBWhPMsxSzW1ouCfROcrsU.2/vDJy', 'gabib97@yahoo.com', 'Gabriel Boroghină', 2, null);
--
-- insert into users(username, password, email, name, role_id, email_verification_token)
-- values ('pw', '$2a$05$zmL1QTEEHvIIvD2YlNEffeXjQXRgRMrsW79pyOHsMc8PEiw1nkjne', 'md.medical.net@gmail.com', 'Paul Walker', 2, null);

-- insert into roles values(0, 'admin');
-- insert into roles values(1, 'support');
-- insert into roles values(2, 'user');